// Dados de demonstração para a vitrine pública do painel admin.
// NÃO usar em produção — apenas exemplifica os blocos da página.

export const mockMetricasDiagnosticos = {
  resumo: {
    total_gestantes: 1248,
    dmg: 187,
    overt: 14,
    dmg_overt_total: 201,
    taxa_controle_global: 78.6,
  },
  evolucao_mensal: [
    { mes: "2025-06", gestantes: 78, diagnosticos: 11 },
    { mes: "2025-07", gestantes: 92, diagnosticos: 14 },
    { mes: "2025-08", gestantes: 104, diagnosticos: 16 },
    { mes: "2025-09", gestantes: 118, diagnosticos: 19 },
    { mes: "2025-10", gestantes: 121, diagnosticos: 18 },
    { mes: "2025-11", gestantes: 109, diagnosticos: 17 },
    { mes: "2025-12", gestantes: 96, diagnosticos: 13 },
    { mes: "2026-01", gestantes: 112, diagnosticos: 18 },
    { mes: "2026-02", gestantes: 124, diagnosticos: 21 },
    { mes: "2026-03", gestantes: 131, diagnosticos: 22 },
    { mes: "2026-04", gestantes: 138, diagnosticos: 19 },
    { mes: "2026-05", gestantes: 25, diagnosticos: 4 },
  ],
  momento_diagnostico: {
    retorno1: 64,
    gtt_janela: 98,
    gtt_tardio: 25,
    ig_retorno1: 9.2,
    ig_gtt_janela: 26.4,
    ig_gtt_tardio: 32.1,
  },
  historico_dmg: {
    pacientes_com_historico: 142,
    dmg_entre_com_historico: 51,
  },
  tratamento: {
    so_dieta: 121,
    insulina_inicial_ok: 26,
    cenario7: 18,
  },
  funil: [
    { etapa: "Total gestantes", valor: 1248 },
    { etapa: "DMG confirmado", valor: 187 },
    { etapa: "Só dieta", valor: 121 },
    { etapa: "Insulina iniciada", valor: 48 },
    { etapa: "Insulina suficiente", valor: 26 },
    { etapa: "Associar endócrino", valor: 18 },
  ],
  desfechos: {
    partos_total: 174,
    via_vaginal: 102,
    via_cesarea: 72,
    rn_aig: 138,
    rn_gig: 24,
    rn_pig: 12,
    peso_medio_g: 3280,
    ig_parto_media: 38.4,
    interc_maternas: 11,
    interc_neonatais: 7,
  },
  regional: {
    por_estado: [
      { estado: "SP", gestantes: 412, dmg: 64, taxa_dmg: 15.5 },
      { estado: "RJ", gestantes: 218, dmg: 31, taxa_dmg: 14.2 },
      { estado: "MG", gestantes: 196, dmg: 28, taxa_dmg: 14.3 },
      { estado: "RS", gestantes: 142, dmg: 22, taxa_dmg: 15.5 },
      { estado: "PR", gestantes: 118, dmg: 17, taxa_dmg: 14.4 },
      { estado: "BA", gestantes: 92, dmg: 14, taxa_dmg: 15.2 },
      { estado: "PE", gestantes: 70, dmg: 11, taxa_dmg: 15.7 },
    ],
    por_cidade: [
      { cidade: "São Paulo", estado: "SP", gestantes: 248, dmg: 39, taxa_dmg: 15.7 },
      { cidade: "Rio de Janeiro", estado: "RJ", gestantes: 164, dmg: 24, taxa_dmg: 14.6 },
      { cidade: "Belo Horizonte", estado: "MG", gestantes: 118, dmg: 18, taxa_dmg: 15.3 },
      { cidade: "Porto Alegre", estado: "RS", gestantes: 96, dmg: 15, taxa_dmg: 15.6 },
      { cidade: "Curitiba", estado: "PR", gestantes: 84, dmg: 12, taxa_dmg: 14.3 },
      { cidade: "Salvador", estado: "BA", gestantes: 71, dmg: 11, taxa_dmg: 15.5 },
      { cidade: "Recife", estado: "PE", gestantes: 58, dmg: 9, taxa_dmg: 15.5 },
      { cidade: "Campinas", estado: "SP", gestantes: 52, dmg: 8, taxa_dmg: 15.4 },
    ],
    por_unidade: [
      { unidade: "Hospital Sofia Feldman", cidade: "Belo Horizonte", estado: "MG", gestantes: 86, dmg: 14, taxa_dmg: 16.3 },
      { unidade: "Maternidade Escola UFRJ", cidade: "Rio de Janeiro", estado: "RJ", gestantes: 74, dmg: 11, taxa_dmg: 14.9 },
      { unidade: "HU-USP", cidade: "São Paulo", estado: "SP", gestantes: 68, dmg: 10, taxa_dmg: 14.7 },
      { unidade: "HC-FMRP", cidade: "Ribeirão Preto", estado: "SP", gestantes: 54, dmg: 9, taxa_dmg: 16.7 },
      { unidade: "HCPA", cidade: "Porto Alegre", estado: "RS", gestantes: 48, dmg: 7, taxa_dmg: 14.6 },
    ],
  },
};
