project_id = "ywldvotfgbxufcyjdvnq"

[functions]
  [functions.asaas-webhook]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.limpar-exportacoes-admin]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.seed-demo-gestor-geral]
    verify_jwt = false
  [functions.seed-demo-gestor-geral-cleanup]
    verify_jwt = false
  [functions.seed-test-accounts]
    verify_jwt = false
